### ISSUE TITLE
Best option for key bindings?

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/script-runner#1]
The current proposed bindings ctrl-shift-x for run and ctrl-shift-z are easy to hit but possibly non-intuitive and not very similar to OS X key bindings, especially in relation to other editors. Wondering if there is a better option or if we should change the OS X key bindings to match?

On Mac OS X:
- TextMate: Command-R to run
- Sublime Text: Command-B to run (???)

On Linux:
- Terminal: Ctrl-C to interrupt

**Comment by ioquatix** [comment]
@huba12 did you have some ideas about key bindings?

**Comment by huba** [comment]
What about Ctrl+Shift+X/C? That might follow atom's key binding pattern, for example there is Ctrl+F for find in current buffer and Ctrl+Shift+F for find in current project. But I also think Ctrl+Alt+X/C is a good idea mentioned earlier by @pezcode . I'm guessing we should also stay away from the super key.

**Comment by ioquatix** [comment]
The big problem I couldn't overcome was trying to use natural terminal comands, e.g. Ctrl-C to send interrupt. But that wasn't possible because it's copy in an editor. In the terminal, copy is Ctrl-Shift-C which is annoying because it's different from everywhere else.

On OSX, Copy is Super-C, so Ctrl-C is free to use. On TextMate, Run is Super-R which is sort of intuitive, but it's a long way to stretch your fingers.

I think that the ideal key bindings are different for each platform, and it would be nice if they followed standard conventions as much as possible..?

**Comment by jerry40** [comment]
Guys, it seems that keybindings for windows are broken.
File script-runner.cson contains binding for linux and darwin only. So after installation on windows, script-runner is not working (from user point of view).

Are we going to add win32 keybindings there? Or is there a reason to not bind the keys on windows?

'.platform-win32 atom-text-editor':
  'alt-x': 'run:script'

'.platform-win32 atom-workspace':
  'alt-c': 'run:terminate'

**Comment by ioquatix** [comment]
Sorry, right now, Windows is not supported completely. https://github.com/ioquatix/script-runner/issues/5 (help wanted :)

**Comment by jerry40** [comment]
Thanks. About help... Why not? Is it a cofee script that uses some external interpreters like nodejs? I would like to participate if you tell me how. I think I'm able to spend couple of hours per week to get some new experience.
Now the package breaks when it tries to get some environment values, I guess.

**Comment by ioquatix** [comment]
So, we fixed the environment problem (or moved it at least) into `shell-environment` so verifying that it least works on Windows would be useful.

The second issue is getting a terminal emulator which supports a pseudo-tty device (pty) so that we can get coloured output on Windows, a couple of options have been considered, e.g. conemu (http://conemu.github.io). I don't have access to a Windows box to test, but it might make sense to have a separate class, one for Unix and one for Windows that just does the right thing - or perhaps an external package which abstracts this. I'm open to suggestions. I'd do it myself but I don't use Windows so can't really justify the investment of time..

**Comment by ioquatix** [comment]
If we can't use a `pty`, perhaps implementing a fallback mode which just runs the command. But another problem here is that currently we get "interactive" output. Otherwise, the output may be buffered by the OS and this is pretty annoying for user since there would be no output until the output buffer is full, and then suddenly lots of output. Again, open to suggestions here.

**Comment by jerry40** [comment]
I installed the package 2 days ago, does it include this fix? If so, the problem still exists. I'll put error text bit later. Need to retest it though.
Or do you mean I need to install shell-environment and test how it works in win? I'm doing this tonight.

**Comment by jerry40** [comment]
script-runner , version 1.8.3, windows 8

TypeError: Bad argument
  at TypeError (native)
  at ChildProcess.spawn (child_process.js:1119:26)
  at Object.exports.spawn (child_process.js:977:9)
  at ShellEnvironment.getLoginEnvironmentFromShell (C:\Users\Evgeny\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:59:28)
  at ShellEnvironment.getBestEnvironment (C:\Users\Evgeny\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:47:19)
  at ShellEnvironment.getEnvironment (C:\Users\Evgeny\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:36:14)
  at Function.ShellEnvironment.loginEnvironment (C:\Users\Evgeny\.atom\packages\script-runner\node_modules\shell-environment\lib\index.js:92:36)
  at ScriptRunner.run (C:\Users\Evgeny\.atom\packages\script-runner\lib\script-runner.coffee:95:22)
  at atom-workspace.atom.commands.add.run:script (C:\Users\Evgeny\.atom\packages\script-runner\lib\script-runner.coffee:32:33)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Evgeny\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\Evgeny\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Evgeny\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Evgeny\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Evgeny\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:180:20)

**Comment by iarmpheeba10** [comment]
wow

**Comment by ioquatix** [comment]
![wow](http://dogr.io/doge.png)

**Comment by ioquatix** [comment]
This issue is getting way off track so I'm going to close it. @jerry40 we are currently discussing using pty.js which should improve windows support.

**Comment by mangueLinux** [comment]
alt is bad if you use ubuntu.

**Comment by ioquatix** [comment]
@mangueLinux can you open a new issue with all the details and preferred key bindings?

**Comment by tomptaylor** [comment]
better instructions, have no idea on how this works!

**Comment by oscar-SHIFT** [comment]
Hi @ioquatix 
This package is great ive been using on mac while learning python
But ive switched to windows, any chance it will be windows compatible ?
cheers
