### ISSUE TITLE
the shell does indeed open but it not possible to write something in it

### ISSUE THREAD

**Issue by bjce** [ioquatix/script-runner#100]
Thank you very much for writting `script-runner` which seems a really nice `atom` package. I installed it successfully. However when I run the command ` ctrl`+ `x`, the shell does indeed pop up as follow: 

<img width="935" alt="screenshot 2018-11-05 at 19 27 27" src="https://user-images.githubusercontent.com/27978044/48018357-eb782700-e130-11e8-8df4-0c9ed3e32f9b.png">

It executes the code in the script. However, i can't write anything in it. Is it possible to write just one line of code it into the shell (for example just the second line `print("hello earth")`). If yes do you have any idea how to fix this?

**Comment by ioquatix** [comment]
You cannot enter additional code into the terminal that comes up.

If you want a shell, use `Script Runner: Shell` and then run `python`. You can enter commands interactively.

**Comment by KieranHo** [comment]
Thanks!
This was also my problem too.
