### ISSUE TITLE
SCRIPT-RUNNER WONT INSTALL

### ISSUE THREAD

**Issue by Yash10bloodstorm** [ioquatix/script-runner#104]
i installed xcode cmd line tools, now what?
should i hit install again
i tried installing using pip install script-runner and it returned:
Requirement already satisfied: script-runner in /Library/Python/2.7/site-packages (0.2.3)
but if i go into atom and see its not installed

See also https://github.com/ioquatix/script-runner/issues/99

**Comment by Yash10bloodstorm** [comment]
https://github.com/ioquatix/script-runner/issues/99#issuecomment-508899509
HELP!!!

**Comment by ioquatix** [comment]
Can you try removing and installing the package within Atom.

**Comment by Yash10bloodstorm** [comment]
you mean like all the packages

**Comment by Yash10bloodstorm** [comment]
i also tried pip3 install script-runner and it did install according to the terminal but when i open atom it has not been installed yet

**Comment by ioquatix** [comment]
`pip` has almost nothing to do with installing script runner, you need to install it using `apm` or the Package Install under Atom.

**Comment by ioquatix** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/30030/60753256-9bd15e80-a023-11e9-99ae-19fe0e8f74eb.png">

Press "Install" button. If it's already installed, uninstall it and reinstall it.

**Comment by ioquatix** [comment]
It look like it might still be a bug with atom: https://github.com/atom/atom/issues/15925

**Comment by ioquatix** [comment]
Also, please check the instructions at the end of https://github.com/ioquatix/script-runner/issues/103
