### ISSUE TITLE
Unlisted dependency that python(2) must be installed to install this package

### ISSUE THREAD

**Issue by uberfuzzy** [ioquatix/script-runner#106]
All the recent install failing tickets end up getting pointed either a problem with `python` vs `python2` or something involving node-gyp which requires python (the fail logs say as much),

```
gyp verb could not find "python". checking python launcher 
gyp verb could not find "python". guessing location 
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
```

but nowhere in the README nor install data does it list that you have to have python on your system to install this, even if you are not using it for running python.

Can you please add a *Dependencies* or *Requirements* section to the README that lists that python2 MUST be installed to install this package?

**Comment by ioquatix** [comment]
Please submit a PR with the proposed improvements.

- Unfortunately whether this works on Windows is still an open question.
- I was under the impress that python2.7 is a required part of Atom/Node.JS for building anything (e.g. gyp)
- We cannot solve issues relating to `node-gyp` here, it's a general problem with Node which I wish they would resolve upstream.
