### ISSUE TITLE
Rebuild failed in 2.5.0 on Atom 1.52.0 

### ISSUE THREAD

**Issue by wjandrea** [ioquatix/script-runner#111]
I got a notification, "Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom." So I clicked "Rebuild Packages", but it failed. Here's a screenshot and the [full error text](https://github.com/ioquatix/script-runner/files/5396627/script-runner_error.txt).

![Screenshot from 2020-10-17 17-03-03](https://user-images.githubusercontent.com/22385371/96353564-4051a580-109b-11eb-828e-4cbafc122ef6.png)

I'm using Ubuntu 18.04 if that's important

#110 seems to be the same issue

**Comment by wjandrea** [comment]
Here's the log: [2020-10-17T21_02_19_627Z-debug.log](https://github.com/ioquatix/script-runner/files/5396664/2020-10-17T21_02_19_627Z-debug.log)

**Comment by ioquatix** [comment]
Okay let me try rebuilding it locally. Maybe a dependency needs to be updated.

**Comment by ioquatix** [comment]
Thanks for your log file. It appears you were trying to use `node-pty` 0.8.x but it has some issues. I've updated the dependency and released script runner v2.6.0 - can you please try it and let me know if it fixes your issue?

**Comment by wjandrea** [comment]
Yes, it's working now, thanks!
