### ISSUE TITLE
Failed to load the script runner package

### ISSUE THREAD

**Issue by MariobrosU22** [ioquatix/script-runner#117]
![image](https://user-images.githubusercontent.com/97406208/155882103-a5502972-b356-4cae-afd6-94b1b512fb18.png)

Just install the package and this happens, I have no clue why.
I'm using windows 10 64 bit

**Comment by MariobrosU22** [comment]
I fixed it myself

**Comment by wjandrea** [comment]
How did you fix it? I'm getting the same error: #119

**Comment by ioquatix** [comment]
I had the same problem with 2.6.0 which is why I released 2.6.1 - ES modules causing all sorts of chaos not completely compatible with Atom / Electron. So I attempted to pin then packages to compatible versions.
