### ISSUE TITLE
Update documentation with new features

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/script-runner#12]
@huba Are you able to update the documentation for the multiple runners functionality you just implemented?

**Comment by huba** [comment]
I'm not sure if this is a good explanation. https://github.com/ioquatix/script-runner/commit/3b995fb0a037bd3f3a840f5af2095701b0f4bb30

**Comment by ioquatix** [comment]
This is great, even just a small amount of documentation is awesome because it helps people new to the project understand how things work.

**Comment by ioquatix** [comment]
Another option is to have a changelog, probably in the README, which outlines major new features and changes.

**Comment by ioquatix** [comment]
Feel free to add any more documentation when you add new features, etc.
