### ISSUE TITLE
Provide public API

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/script-runner#16]
I'd like to include support for a public API so that additional packages can hook into the script-runner infrastructure.

For example, the current latex package suffers from issues due to incorrectly loading users environment. I'd really like to create a new package, say, `script-runner-latex` which can add commands specifically for latex documents, running, say, the `lualatex` command, and updating the output window with the PDF.

**Comment by huba** [comment]
So you essentially want to expose the view and the runner process object and add custom events for the script finishing executions, we might want to move the environment extraction out of the ScriptRunner class into the ScriptRunnerProcess class.

**Comment by ioquatix** [comment]
Something like that, yes, but it might need to be more flexible.. e.g. don't display output, or don't make it the primary window, etc.

**Comment by ioquatix** [comment]
We are tracking this issue in https://github.com/ioquatix/script-runner/issues/77
