### ISSUE TITLE
Output window colors do not match the atome theme

### ISSUE THREAD

**Issue by AngelEzquerra** [ioquatix/script-runner#19]
The output window uses black test on a white background, regardless of the selected theme. This is particularly jarring when using the default Atom-Dark theme.

**Comment by ioquatix** [comment]
What would be the best way to theme the window?

**Comment by AngelEzquerra** [comment]
IMHO the window background and text color should be the same as the ones on the regular editor windows.

**Comment by ioquatix** [comment]
The main problem is supporting terminal text colours, whether it is possible to theme it correctly or not. Right now it is black text on a white background. I will have to have a play around with the CSS.

**Comment by ioquatix** [comment]
@AngelEzquerra this is going to be fixed in the next release, the PR for it has already been merged.
