### ISSUE TITLE
Add support for nim scripts

### ISSUE THREAD

**Issue by AngelEzquerra** [ioquatix/script-runner#20]
It would be nice to add native support for running num scripts.
Nim scripts can be run with the following command:

    nim compile --run scriptpath.nim

Where "scriptpath.nim" is the path to the nim script that is to be run

**Comment by ioquatix** [comment]
Can it run from `stdin` too? for unsaved files.

**Comment by AngelEzquerra** [comment]
Not as far as I know.

**Comment by ioquatix** [comment]
The advice I have received is for you to use https://github.com/flaviut/nimrun
