### ISSUE TITLE
Fresh install cannot console.log a "yolo".

### ISSUE THREAD

**Issue by amingilani** [ioquatix/script-runner#29]
My file `test.js` contains a single line `console.log('yolo');`

Running `node test.js` returns `yolo`.

```
Script Runner: test.js

Running: node /home/user/app/test.js (pgid 28159)
Traceback (most recent call last):
  File "/home/user/.atom/packages/script-runner/lib/script-wrapper.py", line 75, in <module>
    except FileNotFoundError as error:
NameError: name 'FileNotFoundError' is not defined
Exited with status 1 after 0.053 seconds
```

Edit: even `node /home/user/app/test.js` outputs `yolo`.

**Comment by huba** [comment]
It seems like there is an issue with the env setup. Our script wrapper (used for emulating pty) only runs on python 3 it's shebang line reads:
```python
#!/usr/bin/env python
```
Make sure you have python 3.x on your system

**Comment by ioquatix** [comment]
it should also support python 2.7

**Comment by huba** [comment]
@ioquatix python 2.7 doesn't have the FileNotFoundError.

**Comment by ioquatix** [comment]
I've just released 1.7.3 which fixes this could you please check and report back? Thanks.

**Comment by amingilani** [comment]
```
Script Runner: test.js

Running: node /home/user/test.js (pgid 3774)
yolo
Exited with status 0 after 0.094 seconds
```

Thank you @ioquatix!

**Comment by ioquatix** [comment]
@amingilani No problem, thanks for reporting the issue :) Please share script-runner with all your friends and let us know how we can improve it.
