### ISSUE TITLE
How do I add my own extensions?

### ISSUE THREAD

**Issue by jchannon** [ioquatix/script-runner#32]
Your repo says I can configure this to run my own scripts. Where do I do that?

**Comment by jchannon** [comment]
ah I need a shebang line

**Comment by ioquatix** [comment]
You theoretically can also add scope based scripts, but I'm actually not sure off the top of my head how you do it now.

**Comment by huba** [comment]
We could put the command map into the options file for the user to edit. But shebang lines are still the most recommended.

**Comment by ioquatix** [comment]
Documenting this makes a lot of sense to me.

**Comment by ioquatix** [comment]
This is now documented. https://github.com/ioquatix/script-runner#shebang-lines
