### ISSUE TITLE
Choose where to create a new pane.

### ISSUE THREAD

**Issue by NikoUY** [ioquatix/script-runner#34]
It would be nice to being able to choose where the pane is created, the fact that currently splits to the right makes it really inconvinient if you already use a vertical pane like me.

Maybe also including an option to open a new tab instead of creating a new pane could be handy for some people.

**Comment by ioquatix** [comment]
I agree, are you able to submit a PR?

**Comment by Gabriel-p** [comment]
:+1: also would love to have this option.

**Comment by ioquatix** [comment]
How would the option work? Can you spec it out what you'd like exactly?

**Comment by Gabriel-p** [comment]
The `Sublime` package [SublimeREPL](https://github.com/wuub/SublimeREPL) implements this option like so:

````
{
    // Specify whether to move repls to a different Sublime Text group (frame)
    // immediately on opening. Setting this to true will simply move it to
    // the 'next' group from the one that was in focus when it was opened
    // (one down with row layout, one to the right with column and grid
    // layout). Alternatively, you can set this to the index of the group in
    // which you want all repls to be opened (index 0 being the top-left group).
    // Activating this option will NOT automatically change your layout/create
    // a new group if it isn't open.
    "open_repl_in_group": 2,
}
````

The panes are thus numbered starting from 0 with the default top-left pane and increasing clock-wise.

**Comment by ioquatix** [comment]
Can we do the same with Atom?

**Comment by Gabriel-p** [comment]
You mean open different panes? Sure: `View / Panes`

**Comment by ioquatix** [comment]
Right but I'm wondering if the indexing system in that comment makes sense w.r.t. how Atom deals with Panes - I'm all for a PR which implements this. While something more flexible might be the final outcome, this would be an awesome first step.

**Comment by Gabriel-p** [comment]
Can't help you there, I'm just the idea guy :)

Really, I'd love to help out but I can't code in CoffeScript (or Ruby, Or Java,..., only Python)

**Comment by ioquatix** [comment]
This is now supported in 2.0.0 release.
