### ISSUE TITLE
User input on python

### ISSUE THREAD

**Issue by tiferrei** [ioquatix/script-runner#41]
Hi, can I use raw_input with this package?

Thanks,
Tiferrei

**Comment by ioquatix** [comment]
Yes this is a good question.

Using `raw_input` or actually `stdin` requires some kind of interactivity which we don't support yet, but it is something I've thought about implementing.

The main issue is that user input for a actual tty isn't simple. However, we could make a simple line input box which might be sufficient for most uses?

What exactly are you trying to do?r

**Comment by tiferrei** [comment]
That would be perfect for me for example! I'm a teen but I already did some programming on some iOS apps and Xcode but now I'm learning python at my school and I really got used to Atom, plus I hate the official IDLE. So it would be something really simple but yet I need tu use raw_input. :/

**Comment by aplaceforallmystuff** [comment]
I'd second this! I'm using Atom / Script Runner for an upcoming programming publication and just realised I've got to switch the readers back over to IDLE to get their code to work for raw_input.

**Comment by ioquatix** [comment]
I'd love to support `raw_input` or, input from stdin. Any ideas?

**Comment by ioquatix** [comment]
Okay so we are going to investigate Terminal.js which allows for stdin to be used.. it won't be until the weekend probably but we will try to make it work soon.

cc @huba

**Comment by benrob0329** [comment]
Any news on this?

**Comment by ioquatix** [comment]
@benrob0329 Honestly I'm not working much on this project any more. It's basically feature complete for my use case. However, I also thought a bit more about it. These days, when I'm doing stuff that requires to execute a script, I normally run a terminal side by side with Atom. It's working really well and does everything I expect. Script runner, and the general concept of running scripts within your editor isn't a bad idea, but I'm not sure it can be improved all that much. It's just better to use a real terminal.

**Comment by huba** [comment]
So I've worked on this a while ago and now tidied it up (so that it is not completely broken). In PR #52 . I t doesn't look too great yet, but I am open to feedback about how you guys think interactivity should work.

**Comment by ioquatix** [comment]
With 2.0.0 just released, this now works.
