### ISSUE TITLE
No such file or directory while trying to execute node

### ISSUE THREAD

**Issue by abcdedf** [ioquatix/script-runner#46]
I just installed script runner and wrote a simple Hello World js testing it out. When I run it, I get the above error. What could be wrong in my set up? Node installed and working.

**Comment by ioquatix** [comment]
What does the script look like?

**Comment by joeperks** [comment]
I am seeing the same error. I installed node via homebrew. 

I can run the command "node /Users/username/jslearn/learn.js" in the terminal without issue.

**Comment by erelsgl** [comment]
Same error here.   The contents of the file are irrelevant. The issue is probably that on Ubuntu, the program is called "nodejs" rather than "node".   In atom-runner, the solution was to put the following into config.cson:

```
  runner:
    extensions:
      ...
    scopes:
      ...
      **js: "nodejs"**
      ...
```

But, this does not work with script-runner.

**Comment by huba** [comment]
Use a shebang line at the start of your script. script-runner is made to obey [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) lines.

`#!/usr/bin/env node` is what you want to put at the start of the file.

Also I think [this post](http://stackoverflow.com/questions/20638520/appropriate-hashbang-for-node-js-scripts) from StackOverflow is relevant.
