### ISSUE TITLE
How to run a single Mocha test

### ISSUE THREAD

**Issue by erelsgl** [ioquatix/script-runner#49]
I want to run a single Mocha test. 

When I stand inside the file and click "Alt+X", script-runner executes the file with Node.JS instead of Mocha, which of course causes errors.

When I add the following shebang line at the top of the file:

```
 #!/usr/bin/env mocha
```

or just:

```
 #!mocha
```

Mocha runs on all tests in the test folder, rather than just on the current file.

How can I run Mocha on the current file only?

**Comment by huba** [comment]
Does the script runner view say:
`Running: /usr/bin/env mocha <path to test> (pgid <some number>)`
under the title?

**Comment by erelsgl** [comment]
OK... now I get a different error. I click Alt+X, I see this:

    Running: /usr/bin/env mocha <path to test> (pgid 4474)

and the test is run twice (I see the output of the test twice, one below the other).

**Comment by huba** [comment]
This is getting weird. *cue the X-Files theme*

What happens when you open up a terminal and go to wherever the test is and execute:

`/usr/bin/env mocha test-name.js`

**Comment by erelsgl** [comment]
From the terminal, the test runs only once.

**Comment by ioquatix** [comment]
@erelsgl we are looking to move to pty.js and this may fix the issue.. hold tight :)

**Comment by ioquatix** [comment]
@erelsgl Can you test on 2.0.0 which was just released and let us know if this is still an issue.

**Comment by ioquatix** [comment]
Additionally, if you can provide the source file or files, or git repo we can test on our end.
