### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by pezcode** [ioquatix/script-runner#5]
I just installed script-runner on Windows and noticed that keymaps/script-runner.cson only has entries for Mac and Linux, in spite of what the readme mentioned.
After adding shortcuts for .platform-win32 I tested it with a sample python script but nothing really happens.

Does script-runner support Windows or is there a problem on my end? If there's some way to troubleshoot, I'd appreciate a pointer since I have no idea how to debug Atom packages.

**Comment by ioquatix** [comment]
Do you know if windows supports virtual PTY?

**Comment by ccoenen** [comment]
I haven't heard of it, that does not mean it doesn't. How could i test that? Is there any program that uses it, that i could look into for reference?

**Comment by ioquatix** [comment]
@huba was trying out something called child_pty - does that work on windows?

**Comment by huba** [comment]
[child_pty](https://github.com/Gottox/child_pty) doesn't work on Windows, but it has a similar C binding to [ptyjs](https://github.com/chjj/pty.js/) which uses [winpty](https://github.com/peters/winpty) to simulate pty on Windows with a background process.

**Comment by ccoenen** [comment]
You also might want to take a look at [cmder](http://bliker.github.io/cmder/), which is an awesome shell replacement. They also hide the actual console and display it in a fancier way. Maybe there is something to be learned.

Actually, i think the part of cmder that does this, is [conemu](https://code.google.com/p/conemu-maximus5/).

**Comment by ioquatix** [comment]
Consider removing windows support for now.. https://github.com/ioquatix/script-runner/pull/27

**Comment by ioquatix** [comment]
Yes, lets remove windows support until we officially support it.

**Comment by maasha** [comment]
So installing script-runner on windows yields nasty install err. How about just stating that it won't work on windows for now?

```
Updating to “script-runner@2.0.1” failed.Hide output…
INFO: Could not find files for the given pattern(s).

The system cannot find the file specified.


> pty.js@0.3.1 install C:\Users\IEHDK\AppData\Local\Temp\apm-install-dir-1161114-11140-u8xupj\node_modules\script-runner\node_modules\pty.js
> node-gyp rebuild


C:\Users\IEHDK\AppData\Local\Temp\apm-install-dir-1161114-11140-u8xupj\node_modules\script-runner\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\IEHDK\AppData\Local\atom\app-1.12.6\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\IEHDK\AppData\Local\atom\app-1.12.6\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
C:\Users\IEHDK\AppData\Local\Temp\apm-install-dir-1161114-11140-u8xupj
`-- (empty)


gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Users\IEHDK\AppData\Local\atom\app-1.12.6\resources\app\apm\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\Users\IEHDK\AppData\Local\atom\app-1.12.6\resources\app\apm\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at C:\Users\IEHDK\AppData\Local\atom\app-1.12.6\resources\app\apm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Users\\IEHDK\\AppData\\Local\\atom\\app-1.12.6\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\IEHDK\\AppData\\Local\\atom\\app-1.12.6\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\IEHDK\AppData\Local\Temp\apm-install-dir-1161114-11140-u8xupj\node_modules\script-runner\node_modules\pty.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\IEHDK\AppData\Local\Temp\apm-install-dir-1161114-11140-u8xupj\package.json'
npm WARN apm-install-dir-1161114-11140-u8xupj No description
npm WARN apm-install-dir-1161114-11140-u8xupj No repository field.
npm WARN apm-install-dir-1161114-11140-u8xupj No README data
npm WARN apm-install-dir-1161114-11140-u8xupj No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\IEHDK\\AppData\\Local\\atom\\app-1.12.6\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\IEHDK\\AppData\\Local\\atom\\app-1.12.6\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\IEHDK\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\IEHDK\\.atom\\.apmrc" "install" "C:\\Users\\IEHDK\\AppData\\Local\\Temp\\d-1161114-11140-1ar8jt5\\package.tgz" "--runtime=electron" "--target=1.3.9" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\IEHDK\AppData\Local\Temp\apm-install-dir-1161114-11140-u8xupj\npm-debug.log
npm ERR! code 1
```

**Comment by ioquatix** [comment]
Hmm.. this is not a problem with script-runner directly, but a problem with pty.js - other projects have pty.js forks running on windows.. perhaps need to investigate.

**Comment by ioquatix** [comment]
In theory we should have better windows support now, as we use node-pty.js which itself is used by VS code. Please test and file a new issue if still problems.

**Comment by ccoenen** [comment]
Installation works, but running it does not. I'll open a separate ticket for that after going over the issue tracker.

# to install this:

* install python 2
* set my python version for apm explicitly (it picked up my python3, which is not supported by gyp/node-gyp). After this, it was installed just fine.
  ```
  apm config set python  <where ever your python.exe from python 2 is located>
  ```
* follow the other [installation instructions of node-gyp for windows](https://github.com/nodejs/node-gyp#on-windows), namely, you need some way of compiling code.
* after that, `apm install script-runner` ran fine.

**Comment by ioquatix** [comment]
@ccoenen those are awesome instructions, do you want to make a PR for the README?
