### ISSUE TITLE
No config button

### ISSUE THREAD

**Issue by RenaKunisaki** [ioquatix/script-runner#50]
For some reason the settings button doesn't appear in the package info in Atom preferences.

**Comment by ioquatix** [comment]
I don't believe there is any user editable configuration. What are you looking for?

**Comment by RenaKunisaki** [comment]
Sorry, I think I had the versions mixed up. The latest checkout from Github does have config, and I was wondering why I didn't see it in the UI...

**Comment by ioquatix** [comment]
Ah okay, yeah I think we still need to do a release of the latest changes. @huba ?
