### ISSUE TITLE
Broken linecount

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/script-runner#54]
@huba I'm just giving you shit because I can.

**Comment by ioquatix** [comment]
:)

**Comment by ioquatix** [comment]
Apart from that it looks good.

**Comment by ioquatix** [comment]
Oh, actually, remove :first-child doesn't work too well on the logo.rb example, it's removing individual characters.

**Comment by huba** [comment]
Should we just pull in termjs or something like that and have a full blown terminal emulator?

**Comment by ioquatix** [comment]
That would be awesome.. what are the pros and cons?

**Comment by huba** [comment]
The only con I can see is more dependencies.

**Comment by ioquatix** [comment]
That's the JavaScript way. Need to check if an item is in an array? There is a module for that.

**Comment by ioquatix** [comment]
Okay well I think that termjs would be great. Then this project can focus on the high level UI and API which I really think is more interesting.
