### ISSUE TITLE
Add support for XTerm (... not X11)

### ISSUE THREAD

**Issue by ioquatix** [ioquatix/script-runner#55]
@huba 

https://github.com/sourcelair/xterm.js

**Comment by ioquatix** [comment]
I've created a branch for this: https://github.com/ioquatix/script-runner/tree/55-xterm-support

**Comment by ioquatix** [comment]
I've modified the code to use child_pty and it seems good.

Do you want to have a go at the xterm integration?

**Comment by huba** [comment]
Yep sure.

**Comment by ioquatix** [comment]
I'll muck around with the pty implementation to see if I can't make it work a bit better when the file is not saved.

**Comment by ioquatix** [comment]
@huba @RenaKunisaki Just released 2.0.0 with XTerm/pty.js support. Thanks for your PRs and help.
