### ISSUE TITLE
Installing “script-runner@2.0.1” failed

### ISSUE THREAD

**Issue by wlccgp3** [ioquatix/script-runner#62]
Installing “script-runner@2.0.1” failed.Hide output…

> pty.js@0.3.1 install /tmp/apm-install-dir-11708-29199-ico6dn/node_modules/script-runner/node_modules/pty.js
> node-gyp rebuild

/tmp/apm-install-dir-11708-29199-ico6dn
└── (empty)

/opt/atom/resources/app/apm/node_modules/npm/bin/node-gyp-bin/node-gyp: 5: /opt/atom/resources/app/apm/node_modules/npm/bin/node-gyp-bin/node-gyp: /opt/atom/resources/app/apm/bin/../node_modules/.bin/node-gyp: Permission denied
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-11708-29199-ico6dn/package.json'
npm WARN apm-install-dir-11708-29199-ico6dn No description
npm WARN apm-install-dir-11708-29199-ico6dn No repository field.
npm WARN apm-install-dir-11708-29199-ico6dn No README data
npm WARN apm-install-dir-11708-29199-ico6dn No license field.
npm ERR! Linux 4.4.0-3-deepin-amd64
npm ERR! argv "/opt/atom/resources/app/apm/bin/node" "/opt/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/wanli/.atom/.apm/.apmrc" "--userconfig" "/home/wanli/.atom/.apmrc" "install" "/tmp/d-11708-29199-bp90kh/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11708-29199-ico6dn/npm-debug.log
npm ERR! code 1

**Comment by huba** [comment]
Updating node and npm to more recent versions should fix this issue.

**Comment by ioquatix** [comment]
I've changed to use `node-pty` which should fix this issue in v2.1.0. If this is still a problem can you please re-open this issue? Thanks :)
