### ISSUE TITLE
install package error

### ISSUE THREAD

**Issue by Luna-Papa** [ioquatix/script-runner#63]
Installing script-runner to C:\Users\y_pen\.atom\packages failed

> pty.js@0.3.1 install C:\Users\y_pen\AppData\Local\Temp\apm-install-dir-11708-5244-wz4cah\node_modules\script-runner\node_modules\pty.js
> node-gyp rebuild

C:\Users\y_pen\AppData\Local\Temp\apm-install-dir-11708-5244-wz4cah\node_modules\script-runner\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\y_pen\AppData\Local\atom\app-1.9.9\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )

gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\y_pen\AppData\Local\Temp\apm-install-dir-11708-5244-wz4cah\node_modules\script-runner\node_modules\pty.js) while loading dependencies of binding.gyp while trying to load binding.gyp
gypnpm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\y_pen\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\y_pen\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\y_pen\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\y_pen\\.atom\\.apmrc" "install" "C:\\Users\\y_pen\\AppData\\Local\\Temp\\d-11708-5244-ksu1js\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

**Comment by huba** [comment]
Same as #62
