### ISSUE TITLE
npm install Failed

### ISSUE THREAD

**Issue by Luna-Papa** [ioquatix/script-runner#65]
I download the “scirpt-runner” zip,use “npm install” to install the package，but still failed，like this：
<pre>
C:\Users\y_pen\.atom\packages\script-runner>npm install

> pty.js@0.3.1 install C:\Users\y_pen\.atom\packages\script-runner\node_modules\pty.js
> node-gyp rebuild

C:\Users\y_pen\.atom\packages\script-runner\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp: deps\winpty\winpty.gyp not found (cwd: C:\Users\y_pen\.atom\packages\script-runner\node_modules\pty.js) while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\y_pen\.atom\packages\script-runner\node_modules\pty.js
gyp ERR! node -v v7.4.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\y_pen\.atom\packages\script-runner\npm-debug.log
</pre>

**Comment by ioquatix** [comment]
I've changed to using `node-pty` which advertises Windows support developed by Microsoft. Can you check the latest version (2.1.0) and see if that improves the situation?

**Comment by ioquatix** [comment]
@Luna-Papa if you have time can you please try again?

**Comment by ioquatix** [comment]
Please make a new issue if you continue to have issues, but this should be fixed now.
