### ISSUE TITLE
Can this plugin be used to execute a script for the current file

### ISSUE THREAD

**Issue by mikeerickson** [ioquatix/script-runner#66]
Short of creating a separate plugin, I am trying to find a plugin which allows me to:

```
1. run a test (mocha, jest, ava, etc) for the current file
2. run `eslint --fix` for the current file
3. beautify `jsbeautify` for the current file
4. run any script agains the current file
- etc
```

I have found plugins to handle 1) and 3) and while there is a plugin for 2) it does not work reliably.

In short, just pass the current file name to any script I wish (add scripts to `config.cson` accordingly)

**Comment by ioquatix** [comment]
We thought about this. Yes, it's an interesting idea. How would it work in the UI?

**Comment by ioquatix** [comment]
Okay, so there is a way to do this indirectly.

Make a file like, "tasks.sh", and make each line, related to what you want to do.

e.g.

```sh
mocha test/file
eslint --fix test/file
```

Then, highlight that line and run using script-runner, it would only execute that one line, so only do what you want.

It's not EXACTLY what you want, but it's one way to achieve something like it.

**Comment by ioquatix** [comment]
I've thought about this, and I think the best option is what I've suggested above. If you have other ideas, please open a PR.
