### ISSUE TITLE
Multiple scroll bars and unable to copy paste output

### ISSUE THREAD

**Issue by anlytcs** [ioquatix/script-runner#70]
Hi was loving your script-runner until I upgraded today.  The output now has a terminal look to it, which is okay, but the terminal frame has its own scroll bar which is really a problem.  

When using mouse scroll wheel you need to scroll within the terminal frame, then move out of that frame to the Atom window to continue scrolling to the bottom.  This is Inconvenient.  

If I want to copy and paste the output somewhere else to read the entire output, it is not possible.  
you can only copy what is currently displayed in the current window.  

Also, if the split is vertical, output is simply truncated.    Anyway to step back to a previous version? 
(this may be a separate bug)

**Comment by anlytcs** [comment]
Hi, I was able to step back to 1.8.4 using APM.  If I get more time, I would love to help you out, but unfortunately I am really busy.  Back to loving you script-runner tool.  

BTW, the version with the problem was 2.1.1

**Comment by ioquatix** [comment]
I agree.

There are pros/cons to the changes we introduced.

Personally, I think it's better from a correctness POV, but the actual output window I think is a bit step backwards.

I'll take look when I have time.

**Comment by ioquatix** [comment]
I've just release v2.2.0 which is a significant upgrade. Do you mind trying it out? Copy and paste is fixed on both macOS and Linux, but on linux now Copy/Paste uses `Ctrl-Chift-{C,V}` as this is really the only sane choice. You can also use the right click context menu.

Any feedback would be appreciated.
