### ISSUE TITLE
Try to switch python version 

### ISSUE THREAD

**Issue by kden416** [ioquatix/script-runner#82]
```
"script-runner":
    python: "/usr/bin/python3"
```
in config.cson not working.
How can i switch version? I need python 3, but default version is 2.7

**Comment by danPadric** [comment]
Hi.

The power of this package is that you can select how the script will run by specifying it in the `shebang` line. Did you try this way yet?

Regards.

**Comment by kden416** [comment]
Yes, but it is not convenient for me.

**Comment by ioquatix** [comment]
This is probably something we should support, but I'm not sure what is the best way yet.

**Comment by danPadric** [comment]
Do you know how to use Atom's API to identify which grammar is used in the
active editor?

**Comment by ioquatix** [comment]
So, script runner already does that. But the interpreters are hard coded.

**Comment by danPadric** [comment]
okay.. then why is @kden416 having an issue if (I assume) he made a change in the hard-coded look-up?
